const PRODUCT_FETCH_SUCCESS = 'PRODUCT_FETCH_SUCCESS';
const PRODUCT_FETCH_FAILURE = 'PRODUCT_FETCH_FAILURE';
const PRODUCT_FETCH_PROGRESS = 'PRODUCT_FETCH_PROGRESS';

export {
    PRODUCT_FETCH_SUCCESS,
    PRODUCT_FETCH_FAILURE,
    PRODUCT_FETCH_PROGRESS
}